spring:
  profiles:
    default: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: NEVER

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  key: abcdefghijklmnopqrstuvwxyz1234567890
  access-token-expiration: 3600000 # 1 day
  refresh-token-expiration: 604800000 # 7 days
