spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:~/jun-chat?MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true
        storage_engine: innodb
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: EMBEDDED

logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: debug
        type.descriptor.sql: trace
      springframework:
        orm:
          jpa: debug
        transaction: debug
